artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  ALL_HUGGINGFACE_DATA: ["d0rj/wikisum", "multi_news"]
  LOCAL_DATA_FILE: ["artifacts/data_ingestion/wikisum", "artifacts/data_ingestion/multi_news"]


data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_DATA: ["wikisum", "multi_news"]
  ALL_REQUIRED_FILES: ["train", "test", "validation"]


data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/
  ALL_REQUIRED_DATA: ["wikisum", "multi_news"]
  tokenizer_name: google/pegasus-cnn_dailymail


model_trainer:
  root_dir: artifacts/model_trainer
  data_path: artifacts/data_transformation/dataset
  model_ckpt: google/pegasus-cnn_dailymail


model_evaluation:
  root_dir: artifacts/model_evaluation
  data_path: artifacts/data_transformation/dataset
  model_path: artifacts/model_trainer/pegasus-summary-lm
  tokenizer_path: artifacts/model_trainer/tokenizer
  metric_file_name: artifacts/model_evaluation/metrics.csv