name: Upload Model to Hugging Face

on:
  push:
    branches:
      - main  # or the branch you want to trigger the action

jobs:
  upload_model:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'  # Specify your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Ensure you have a requirements.txt file with necessary dependencies
        pip install huggingface-hub

    - name: Add remote
      env:
        HF: ${{ secrets.HG }}
      run: git remote add space https://satyam998:$HF@huggingface.co/spaces/satyam998/pegasus-summary-lm

    - name: Push to hub
      env:
        HF: ${{ secrets.HG }}
      run: git push --force https://satyam998:$HF@huggingface.co/spaces/satyam998/pegasus-summary-lm main

